=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/xmlconfig/commandparse.dtd
<!-- 统一正则节点-->
<!ELEMENT Regex (#PCDATA)>

<!-- 属性值转大写节点-->
<!ELEMENT ToUpper EMPTY>
<!--需转大写属性，多个以逗号间隔，缺省只处理第一个属性-->
<!ATTLIST ToUpper name CDATA #IMPLIED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST ToUpper order CDATA #IMPLIED>

<!-- 属性值转小写节点-->
<!ELEMENT ToLower EMPTY>
<!--需转小写属性，多个以逗号间隔，缺省只处理第一个属性-->
<!ATTLIST ToLower name CDATA #IMPLIED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST ToLower order CDATA #IMPLIED>

<!-- 属性设置为指定值节点-->
<!ELEMENT MatchAndSet EMPTY>
<!--属性名称，多个以逗号间隔，缺省只处理第一个属性-->
<!ATTLIST MatchAndSet name CDATA #IMPLIED>
<!--需设置的指定值，多个指定值以逗号间隔，需与name一一对应-->
<!ATTLIST MatchAndSet value CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST MatchAndSet order CDATA #IMPLIED>


<!-- 属性值映射节点-->
<!ELEMENT ValueMapping EMPTY>
<!--属性名称，多个以逗号间隔，缺省只处理第一个属性-->
<!ATTLIST ValueMapping name CDATA #IMPLIED>
<!--需映射属性原值，多种原值以逗号间隔-->
<!ATTLIST ValueMapping srcValue CDATA #REQUIRED>
<!--映射的目标值，多种目标值以逗号间隔，目标值与原值需一一对应-->
<!ATTLIST ValueMapping dstValue CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST ValueMapping order CDATA #IMPLIED>

<!-- 正则表达式提取指定属性值内容节点-->
<!ELEMENT StrExtract EMPTY>
<!--需正则提取属性名称，只支持单个属性正则提取，缺省只处理第一个属性-->
<!ATTLIST StrExtract name CDATA #IMPLIED>
<!--正则表达式-->
<!ATTLIST StrExtract regex CDATA #REQUIRED>
<!--group索引值(整型数值，>=0)，0-表示取正则表达式匹配出的整个字符串、1-表示取正则表达式第1个括号里匹配出的字符串、2-表示取正则表达式第2个括号里匹配出的字符串，依次类推。-->
<!ATTLIST StrExtract groupId CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST StrExtract order CDATA #IMPLIED>

<!-- 默认值节点-->
<!ELEMENT DefaultValue EMPTY>
<!--属性名称，多个以逗号间隔-->
<!ATTLIST DefaultValue name CDATA #REQUIRED>
<!--属性默认值，多个以逗号间隔，与属性名称一一对应-->
<!ATTLIST DefaultValue value CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST DefaultValue order CDATA #IMPLIED>

<!-- 过滤节点，按过滤条件过滤解析记录-->
<!ELEMENT Filter EMPTY>
<!--待过滤属性名，当filterType是NOT_ONLY时，支持多个属性。多个以逗号间隔-->
<!ATTLIST Filter filterFieldName CDATA #REQUIRED>
<!--过滤条件类型,EQUALS:等于；NOT_EQUALS:不等于；CONTAINS:包含；NOT_CONTAINS:不包含；NOT_ONLY:解析结果不仅仅包含待过滤属性;IN:等于多个值，逗号作分割-->
<!ATTLIST Filter filterType (EQUALS|NOT_EQUALS|CONTAINS|NOT_CONTAINS|NOT_ONLY|IN|NULL|NOT_NULL) #REQUIRED>
<!--过滤条件的固定值-->
<!ATTLIST Filter filterValue CDATA #IMPLIED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST Filter order CDATA #IMPLIED>

<!-- 将一个字符串属性值，按照分隔符拆分为多个属性-->
<!ELEMENT SplitField EMPTY>
<!--待进行字符串拆分的属性名，仅支持单个属性，缺省使用Field对应属性-->
<!ATTLIST SplitField srcField CDATA #IMPLIED>
<!--字符串拆分分隔符-->
<!ATTLIST SplitField delimiter CDATA #REQUIRED>
<!--字符串拆分后存放结果值的属性名，多个属性以逗号间隔。若该属性名在原结果数据中存在，则覆盖原值，若不存在则新增属性-->
<!ATTLIST SplitField dstFields CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST SplitField order CDATA #IMPLIED>

<!-- 多个属性合并为一个新的属性-->
<!ELEMENT MergeField EMPTY>
<!--需要合并的属性名列表，两个或多个属性，以逗号间隔-->
<!ATTLIST MergeField srcFields CDATA #REQUIRED>
<!--属性合并分隔符-->
<!ATTLIST MergeField delimiter CDATA #REQUIRED>
<!--存放结果值的目标结果属性名，若该属性在原结果数据中存在，则覆盖原值，若不存在则新增属性-->
<!ATTLIST MergeField dstField CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST MergeField order CDATA #IMPLIED>

<!-- 自定义算子仅用于处理解析属性值map-->
<!ELEMENT CustomOperator EMPTY>
<!--自定义工具类全名-->
<!ATTLIST CustomOperator className CDATA #REQUIRED>
<!--自定义处理类方法名，自定义处理方法入参必须为Map-->
<!ATTLIST CustomOperator methodName CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST CustomOperator order CDATA #IMPLIED>

<!-- 字符串替换节点-->
<!ELEMENT ReplaceAll EMPTY>
<!--属性名称，多个以逗号间隔，缺省只处理第一个属性-->
<!ATTLIST ReplaceAll name CDATA #IMPLIED>
<!--需要替换的字符串，支持正则表达式-->
<!ATTLIST ReplaceAll regex CDATA #REQUIRED>
<!--替换之后的字符串-->
<!ATTLIST ReplaceAll replacement CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST ReplaceAll order CDATA #IMPLIED>

<!-- 给满足条件数据的指定属性赋指定值-->
<!ELEMENT Assign EMPTY>
<!--指定属性赋指定值，指定多个属性时以逗号间隔，格式为field1:value1,field2:value2,value支持设置为#{属性名称}获取指定属性值-->
<!ATTLIST Assign assignMap CDATA #REQUIRED>
<!--待过滤属性名，只支持单个属性正则提取，缺省只处理第一个属性-->
<!ATTLIST Assign filterFieldName CDATA #IMPLIED>
<!--过滤条件类型,EQUALS:等于；NOT_EQUALS:不等于；CONTAINS:包含；NOT_CONTAINS:不包含；START_WITH:开始以；END_WITH:结束以;NULL:为null或空串-->
<!ATTLIST Assign filterType (EQUALS|NOT_EQUALS|CONTAINS|NOT_CONTAINS|START_WITH|END_WITH|NULL|NOT_NULL) #REQUIRED>
<!--过滤条件的固定值-->
<!ATTLIST Assign filterValue CDATA #IMPLIED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST Assign order CDATA #IMPLIED>

<!-- 属性重命名-->
<!ELEMENT RenameField EMPTY>
<!--指定属性名映射关系，指定多个属性时以逗号间隔，格式为oldname1:newname1,oldname2:newname2-->
<!ATTLIST RenameField fieldMap CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST RenameField order CDATA #IMPLIED>

<!-- 字符串拼接算子-->
<!ELEMENT StrConcat EMPTY>
<!--待进行字符串拼接的字段名，仅支持单个属性，缺省使用Field对应属性-->
<!ATTLIST StrConcat srcField CDATA #IMPLIED>
<!--待拼接的前缀字符串，缺省为空串-->
<!ATTLIST StrConcat prefixStr CDATA #IMPLIED>
<!--待拼接的后缀字符串，缺省为空串-->
<!ATTLIST StrConcat suffixStr CDATA #IMPLIED>
<!--存放结果值的目标结果字段名，若该字段名在原结果数据中存在，则覆盖原值，如果不存在则新增字段列-->
<!ATTLIST StrConcat dstField CDATA #REQUIRED>
<!--算子执行顺序，正整数，值越小越优先执行，缺省按DTD约束顺序执行-->
<!ATTLIST StrConcat order CDATA #IMPLIED>

<!-- 属性节点,Field节点下子节点不能重复配置-->
<!ELEMENT Field (Regex?,ToUpper?,ToLower?,MatchAndSet?,ValueMapping?,StrExtract?,SplitField?,CustomOperator?,ReplaceAll?,Assign*,StrConcat?)>
<!--属性名称，多个以逗号间隔，需与ConfigParsePolicy、TableLineParsePolicy、TableColumnParsePolicy下使用的Regex 正则别名相匹配-->
<!ATTLIST Field name CDATA #REQUIRED>
<!--解析属性是否必要，必要属性未解析会终止该节点解析-->
<!ATTLIST Field primary (true|false) #IMPLIED>
<!--解析属性是否需要多行合并，配合TableColumnParsePolicy使用-->
<!ATTLIST Field merge (true|false) #IMPLIED>
<!--属性多行合并的分隔符，缺省不分隔，配合TableColumnParsePolicy使用-->
<!ATTLIST Field mergeDelimiter CDATA #IMPLIED>
<!--属性是否行最后一个，即属性值会一直匹配到行结束，配合TableColumnParsePolicy使用-->
<!ATTLIST Field isEndOfLine (true|false) #IMPLIED>

<!-- 非表格文本解析节点-->
<!ELEMENT ConfigParsePolicy (Field+)>

<!-- 按行解析表格回显节点-->
<!ELEMENT TableLineParsePolicy (Regex,Field+)>

<!-- 按列解析表格回显节点-->
<!ELEMENT TableColumnParsePolicy (Regex,Field+)>
<!--是否支持换行解析-->
<!ATTLIST TableColumnParsePolicy newlineSupport (true|false) #IMPLIED>

<!-- 解析动态列表格回显节点-->
<!ELEMENT DynamicColumnParsePolicy (Field+)>
<!--列数据分隔符，缺省为空格-->
<!ATTLIST DynamicColumnParsePolicy delimiter CDATA #IMPLIED>

<!--待解析节点名称-->
<!ATTLIST ParseNode name CDATA #REQUIRED>
<!--指定设备类型/版本组合，多个以逗号间隔，如果指定该属性那么只有满足条件的设备才会解析节点。缺省不区分设备类型版本-->
<!ATTLIST ParseNode productVersions CDATA #IMPLIED>
<!--ParseNode解析支持读取单独xml配置文件，避免命令解析配置过大-->
<!ATTLIST ParseNode xmlConfigPath CDATA #IMPLIED>
<!--是否支持设置默认值，通过解析策略未解析出结果，也能通过节点及算子添加属性生成节点-->
<!ATTLIST ParseNode supportDefault (true|false) #IMPLIED>

<!--默认节点-->
<!ELEMENT DefaultNode (SegmentParse?)>
<!--默认节点名称-->
<!ATTLIST DefaultNode name CDATA #REQUIRED>
<!--默认节点属性，属性名称:属性值，多个以逗号间隔-->
<!ATTLIST DefaultNode attributes CDATA #REQUIRED>

<!-- 解析节点对应model中的节点
Regex:添加节点需匹配的正则表达式,缺省直接执行后续解析策略
-->
<!ELEMENT ParseNode (Regex?,(ConfigParsePolicy|TableLineParsePolicy|TableColumnParsePolicy|DynamicColumnParsePolicy)?,Filter?,DefaultValue?,MergeField?,CustomOperator?,RenameField?,SegmentParse?)>

<!--分片解析节点-->
<!ELEMENT SegmentParse (Regex?,ParseNode+,DefaultNode?)>
<!--ParseNode子节点解析是否互斥，true-按顺序只解析一种子节点，false-尝试解析所有节点，缺省为false-->
<!ATTLIST SegmentParse childMutex (true|false) #IMPLIED>
<!--分片提取正则group组，缺省时直接按Regex分片-->
<!ATTLIST SegmentParse extractGroupName CDATA #IMPLIED>
<!--使用正则分片时，分片结果是否包含第一段回显，缺省为false不包含-->
<!ATTLIST SegmentParse hasFirst (true|false) #IMPLIED>

<!--通用配置解析根节点-->
<!ELEMENT CommandParseConfig (SegmentParse)>

<!--配置化大命令解析命令具体配置-->
<!ELEMENT CommandParse EMPTY>
<!--回显命令，多个互斥命令使用@@间隔-->
<!ATTLIST CommandParse cmd CDATA #REQUIRED>
<!--命令是否是正则表达式，true-获取所有满足正则的命令回显-->
<!ATTLIST CommandParse isRegexCmd (true|false) #IMPLIED>
<!--回显命令对应解析配置路径。回显命令为多个时，命令处理配置都相同可以合并，存在不相同不能合并必须与回显命令一一对应以@@分隔-->
<!ATTLIST CommandParse path CDATA #REQUIRED>
<!--命令互斥，多个互斥命令时配置，命令回显存在即跳出-->
<!ATTLIST CommandParse isCommandMutex (true|false) #IMPLIED>
<!--解析结果互斥，多个互斥命令时配置，解析结果存在即跳出-->
<!ATTLIST CommandParse isResultMutex (true|false) #IMPLIED>
<!--大命令解析使用，回显独立文件名称，多个以@@间隔，与回显命令一一对应-->
<!--<!ATTLIST CommandParse parseFile CDATA #IMPLIED>-->
<!--大命令解析使用，回显分隔正则多个以@@间隔，与回显命令一一对应，保障回显正确分片-->
<!ATTLIST CommandParse splitRegex CDATA #IMPLIED>

<!--配置化解析采集项节点-->
<!ELEMENT CommonParseItem (VendorCommon+)>

<!--配置化解析厂商项节点-->
<!ELEMENT VendorCommon (CommandParse+)>
<!--厂商名称对应枚举值EnumNeVendorType-->
<!ATTLIST VendorCommon vendor CDATA #REQUIRED>
<!--配置化解析结果后置处理类-->
<!ATTLIST VendorCommon afterClass CDATA #IMPLIED>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/xmlconfig/huawei/display lldp neighbor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
  -->

<!DOCTYPE CommandParseConfig SYSTEM "commandparse.dtd">
<!--
    非CDATA块中使用正则，需转义的特殊字符：< : &lt;  > : &gt;  &: &amp; ' : &apos; " : &quot;
    CDATA代码块：<![CDATA[正则内容]]>
-->
<!-- 回显样例
display lldp neighbor
GigabitEthernet0/0/39 has 1 neighbor(s):

Neighbor index :1
Chassis type   :MAC address
Chassis ID     :xxxx-xxxx-xxxx
Port ID type   :Interface name
Port ID        :GigabitEthernet0/0/1
Port description    :HUAWEI, AC Series, GigabitEthernet0/0/1 Interface
System name         :SHSZUniCity-AC9700S-Master
System description  :Huawei AirEngine9700S-S
-->
<CommandParseConfig>
    <SegmentParse>
        <Regex>^(.{1,255}) has +(\d+) +neighbor(s)?:?</Regex>
        <ParseNode name="lldpNeighborIf">
            <ConfigParsePolicy>
                <Field name="localPortName,neighborNum">
                    <Regex>
                        <![CDATA[
                        ^(?<localPortName>.{1,255}) has +(?<neighborNum>\d+) +neighbor(s)?:?
                        ]]>
                    </Regex>
                </Field>
            </ConfigParsePolicy>
            <Filter filterFieldName="neighborNum" filterType="NOT_EQUALS" filterValue="0"/>
            <SegmentParse>
                <Regex>^ *Neighbor *index {0,100}: {0,100}\d+</Regex>
                <ParseNode name="lldpNeighborNode">
                    <ConfigParsePolicy>
                        <Field name="remotePortId">
                            <Regex>
                                <![CDATA[
                                ^ *Port *Id *: *(?<remotePortId>\S+( +(\d+/){1,5}\d+)?)
                                ]]>
                            </Regex>
                        </Field>
                        <Field name="remoteSystemName">
                            <Regex>
                                <![CDATA[
                                ^ *System *name {0,100}: {0,100}(?<remoteSystemName>.*)
                                ]]>
                            </Regex>
                            <Assign assignMap="remoteSystemName:" filterType="EQUALS" filterValue="--"/>
                        </Field>
                    </ConfigParsePolicy>
                </ParseNode>
            </SegmentParse>
        </ParseNode>
    </SegmentParse>
</CommandParseConfig>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/parseitem/arp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonParseItem SYSTEM "commandparse.dtd">
<CommonParseItem>
    <VendorCommon vendor="HUAWEI">
        <CommandParse cmd="display arp" path="parsecfg/xmlconfig/huawei/display arp.xml"/>
    </VendorCommon>
    <VendorCommon vendor="ZTE">
        <CommandParse cmd="show arp" path="parsecfg/xmlconfig/zte/show arp.xml"/>
    </VendorCommon>
    <VendorCommon vendor="H3C">
        <CommandParse cmd="display arp all" path="parsecfg/xmlconfig/h3c/display arp all.xml"/>
    </VendorCommon>
    <VendorCommon vendor="RUIJIE">
        <CommandParse cmd="show arp" path="parsecfg/xmlconfig/ruijie/show arp.xml"/>
    </VendorCommon>
</CommonParseItem>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/xmlconfig/ruijie/show version.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
  -->

<!DOCTYPE CommandParseConfig SYSTEM "commandparse.dtd">
<!--
    非CDATA块中使用正则，需转义的特殊字符：< : &lt;  > : &gt;  &: &amp; ' : &apos; " : &quot;
    CDATA代码块：<![CDATA[正则内容]]>
-->
<!-- 回显样例
show version
System description      : Ruijie High-density IPv6 100G Core Routing Switch(N18010) By Ruijie Networks
System start time       : 2022-08-31 02:12:23
System uptime           : 411:14:39:35
System hardware version : 1.11
System software version : N18000_RGOS 11.0(4)B19P2
System patch number     : NA
System serial number    : G1L703T00100A
System boot version     : 1.2.27


-->
<CommandParseConfig>
    <SegmentParse>
        <ParseNode name="versionNode">
            <ConfigParsePolicy>
                <Field name="deviceType">
                    <Regex>
                        <![CDATA[
                          ^ {0,100}System\s{1,100}description\s{1,100}:.{0,1024}\((?<deviceType>\S{1,255})\)
                        ]]>
                    </Regex>
                </Field>
                <Field name="deviceVersion">
                    <Regex>
                        <![CDATA[
                          System\s+software\s+version\s+:(?<deviceVersion>.{1,1024})
                        ]]>
                    </Regex>
                </Field>
            </ConfigParsePolicy>
        </ParseNode>
    </SegmentParse>
</CommandParseConfig>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/xmlconfig/zte/show interface brief.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
  -->

<!DOCTYPE CommandParseConfig SYSTEM "commandparse.dtd">
<!--
    非CDATA块中使用正则，需转义的特殊字符：< : &lt;  > : &gt;  &: &amp; ' : &apos; " : &quot;
    CDATA代码块：<![CDATA[正则内容]]>
-->
<!-- 回显样例
show interface brief
Interface               Attribute  Mode         BW    Admin Phy   Prot  Description
cgei-0/1/1/1            optical    Duplex/full  100G  down  down  down
cgei-0/1/1/2            optical    Duplex/full  100G  down  down  down
-->
<CommandParseConfig>
    <SegmentParse>
        <ParseNode name="opticalIfNode">
            <TableLineParsePolicy>
                <Regex>
                    <![CDATA[
                    ^ *(?<ifName>\S+) +optical +
                    ]]>
                </Regex>
                <Field name="ifName">
                    <!--接口名称标准化-->
                    <CustomOperator className="com.huawei.ncetools.ipdevicecheckservice.util.IfNameConvertUtil"
                                    methodName="convertIfName"/>
                    <Assign assignMap="vendor:ZTE" filterType="NOT_NULL" filterFieldName="ifName" order="-2"/>
                </Field>
            </TableLineParsePolicy>
        </ParseNode>
    </SegmentParse>
</CommandParseConfig>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/parseitem/interface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonParseItem SYSTEM "commandparse.dtd">
<CommonParseItem>
    <VendorCommon vendor="HUAWEI">
        <CommandParse cmd="display interface" path="parsecfg/xmlconfig/huawei/display interface.xml"/>
        <CommandParse cmd="display interface brief" path="parsecfg/xmlconfig/huawei/display interface brief.xml"/>
        <CommandParse cmd="display interface transceiver verbose@@display transceiver verbose"
                      path="parsecfg/xmlconfig/huawei/display interface transceiver verbose.xml@@parsecfg/xmlconfig/huawei/display transceiver verbose.xml"
                      isResultMutex="true"/>
        <CommandParse cmd="display optical-module interface \S+@@display transceiver diagnosis interface"
                      isRegexCmd="true" isResultMutex="true"
                      path="parsecfg/xmlconfig/huawei/display optical-module interface.xml@@parsecfg/xmlconfig/huawei/display transceiver diagnosis interface.xml"/>
    </VendorCommon>
    <VendorCommon vendor="ZTE">
        <CommandParse cmd="show interface" path="parsecfg/xmlconfig/zte/show interface.xml"/>
        <CommandParse cmd="show interface brief" path="parsecfg/xmlconfig/zte/show interface brief.xml"/>
        <CommandParse cmd="show opticalinfo \S+@@show optical-inform brief shelf 0" isRegexCmd="true"
                      isResultMutex="true"
                      path="parsecfg/xmlconfig/zte/show opticalinfo.xml@@parsecfg/xmlconfig/zte/show optical-inform brief shelf 0.xml"/>
        <CommandParse cmd="show optical-inform shelf 0" path="parsecfg/xmlconfig/zte/show optical-inform shelf 0.xml"/>
        <CommandParse cmd="show optical-inform details rx-power shelf 0"
                      path="parsecfg/xmlconfig/zte/show optical-inform details rx-power shelf 0.xml"/>
        <CommandParse cmd="show optical-inform details tx-power shelf 0"
                      path="parsecfg/xmlconfig/zte/show optical-inform details tx-power shelf 0.xml"/>
    </VendorCommon>
    <VendorCommon vendor="H3C">
        <CommandParse cmd="display interface" path="parsecfg/xmlconfig/h3c/display interface.xml"/>
        <CommandParse cmd="display transceiver diagnosis interface"
                      path="parsecfg/xmlconfig/h3c/display transceiver diagnosis interface.xml"/>
        <CommandParse cmd="display transceiver interface"
                      path="parsecfg/xmlconfig/h3c/display transceiver interface.xml"/>
    </VendorCommon>
    <VendorCommon vendor="RUIJIE">
        <CommandParse cmd="show interfaces" path="parsecfg/xmlconfig/ruijie/show interfaces.xml"/>
        <CommandParse cmd="show interfaces brief" path="parsecfg/xmlconfig/ruijie/show interfaces brief.xml"/>
        <CommandParse cmd="show interfaces transceiver"
                      path="parsecfg/xmlconfig/ruijie/show interfaces transceiver.xml"/>
    </VendorCommon>
</CommonParseItem>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/parseitem/mac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonParseItem SYSTEM "commandparse.dtd">
<CommonParseItem>
    <VendorCommon vendor="HUAWEI">
        <CommandParse cmd="display mac-address" path="parsecfg/xmlconfig/huawei/display mac-address.xml"/>
    </VendorCommon>
    <VendorCommon vendor="ZTE">
        <CommandParse cmd="show mac table@@show mac" isResultMutex="true"
                      path="parsecfg/xmlconfig/zte/show mac table.xml@@parsecfg/xmlconfig/zte/show mac.xml"/>
    </VendorCommon>
    <VendorCommon vendor="H3C">
        <CommandParse cmd="display mac-address" path="parsecfg/xmlconfig/h3c/display mac-address.xml"/>
    </VendorCommon>
    <VendorCommon vendor="RUIJIE">
        <CommandParse cmd="show mac-address-table" path="parsecfg/xmlconfig/ruijie/show mac address table.xml"/>
    </VendorCommon>
</CommonParseItem>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/parseitem/hardware.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonParseItem SYSTEM "commandparse.dtd">
<CommonParseItem>
    <VendorCommon vendor="HUAWEI">
        <CommandParse cmd="display esn@@display device esn" isResultMutex="true"
                      path="parsecfg/xmlconfig/huawei/display esn.xml"/>
        <CommandParse cmd="display license" path="parsecfg/xmlconfig/huawei/display license.xml"/>
        <CommandParse cmd="display alarm active" path="parsecfg/xmlconfig/huawei/display alarm active.xml"/>
        <CommandParse cmd="display version" path="parsecfg/xmlconfig/huawei/display version.xml"/>
        <CommandParse cmd="display current-configuration | include sysname"
                      path="parsecfg/xmlconfig/h3c/display sysname.xml"/>
    </VendorCommon>
    <VendorCommon vendor="ZTE">
        <CommandParse cmd="show version" path="parsecfg/xmlconfig/zte/show version.xml"/>
        <CommandParse cmd="show running-config | include hostname" path="parsecfg/xmlconfig/zte/show hostname.xml"/>
    </VendorCommon>
    <VendorCommon vendor="H3C">
        <CommandParse cmd="display version" path="parsecfg/xmlconfig/h3c/display version.xml"/>
        <CommandParse cmd="display current-configuration | include sysname"
                      path="parsecfg/xmlconfig/h3c/display sysname.xml"/>
    </VendorCommon>
    <VendorCommon vendor="RUIJIE">
        <CommandParse cmd="show running-config | include hostname"
                      path="parsecfg/xmlconfig/ruijie/show running config include hostname.xml"/>
        <CommandParse cmd="show version"
                      path="parsecfg/xmlconfig/ruijie/show version.xml"/>
    </VendorCommon>
</CommonParseItem>

=== DeavorWei/NetWeaverGo/internal/parser/templates/parsecfg/parseitem/lldp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CommonParseItem SYSTEM "commandparse.dtd">
<CommonParseItem>
    <VendorCommon vendor="HUAWEI">
        <CommandParse cmd="display lldp neighbor@@display lldp neighbor brief"
                      path="parsecfg/xmlconfig/huawei/display lldp neighbor.xml@@parsecfg/xmlconfig/huawei/display lldp neighbor brief.xml"
                      isResultMutex="true"/>
    </VendorCommon>
    <VendorCommon vendor="ZTE">
        <CommandParse cmd="show lldp entry" path="parsecfg/xmlconfig/zte/show lldp entry.xml"/>
    </VendorCommon>
    <VendorCommon vendor="H3C">
        <CommandParse cmd="display lldp neighbor-information list"
                      path="parsecfg/xmlconfig/h3c/display lldp neighbor-information list.xml"/>
    </VendorCommon>
    <VendorCommon vendor="RUIJIE">
        <CommandParse cmd="show lldp neighbors" path="parsecfg/xmlconfig/ruijie/show lldp neighbors.xml"/>
    </VendorCommon>
</CommonParseItem>
